disabled_rules:
  - trailing_whitespace
  - todo
  - large_tuple
  - force_cast
  - function_parameter_count
  - opening_brace

opt_in_rules:
  - closure_spacing
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing

line_length:
  warning: 160
  error: 260

function_body_length:
  warning: 100
  error: 200

type_body_length:
  warning: 500
  error: 800

file_length:
  warning: 600
  error: 1000

identifier_name:
  min_length:
    warning: 1
  excluded:
    - id
    - x
    - y
    - i

excluded:
  - .build
  - DerivedData

reporter: xcode
